---
title: "Background on the data used"
---

```{r, echo = FALSE}
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE)
```

All data are stored at 

# Minke dataset
___

Location: ftp://ftp.hafro.is/pub/tcrenv/minke.csv

The minke whale dataset contains biological measurements from 192 scientific catches of minke whales between the year 2003 and 2007. The data set contains the following fields:

* **whale.id**: Unique identifier for the whale
* **date.caught**: the date when the whales was caught
* **lat**: latitude
* **lon**: longitude
* **area**: Derived from location (North/South)
* **length**: length of the whale (cm)
* **weight**: weight of the whale (kg)
* **age**: age of the whale (years)
* **sex**: Male or Female
* **maturity**: maturity status of the whale
* **stomach.volume**: volume of the stomach content (liters)
* **stomach.weight**: weight of the stomach content (kg)
* **year**: the year when the whale was caught

# iCod_2017 MS-Excel dataset
___

Location: ftp://ftp.hafro.is/pub/tcrenv/iCod_2017.xlsx

Assessment summary of cod in Icelandic waters from 2017, obtained from http://dt.hafogvatn.is/astand/2017/01_cod.html . The data set contains the following fields:

* **Year** 
* **Rec** Recruitment as 3-year-olds in millions
* **SSB**  spawning stock
* **B4+**  reference biomass
* **Landings** landings in tonnes
* **HR** harvest rate (landings/reference biomass)
* **Fbar** fishing mortality (average for ages 5–10)


# Logbook data
___

# DATRAS data
___

# Icelandic groundfish survey data
___



