---
title: "TCRENV - Hafro 2018"
author: "Training Course in the R ENVironment"
output:
  html_document: default
bibliography: mybib.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Preamble
___

### The course material

The course material is open source, meaning that the source code is made freely available and may be redistributed and modified.

* The source code for the course material is located at: https://github.com/fishvice/tcrenv
* The course product is rendered at: http://www.hafro.is/~einarhj/tcrenv

### Your a priori homework

**Prior to the course** please try to install:

* Latest version of __R__: see [The Comprehensive R Archive Network](https://cran.r-project.org/)
    * If your platform is Windows, also install [Rtools](https://cran.r-project.org/bin/windows/Rtools)
   * If your platform is Mac, install **XCode** via AppStore.

* Latest version of __RStudio__: see [RStudio Desktop](https://www.rstudio.com/products/rstudio/download/)
    * If you are adventurous install the latest [developmental version](https://www.rstudio.com/products/rstudio/download/preview)

For those that want to get a head we recommend the following read:

  * [R for Data Science](http://r4ds.had.co.nz) [@wickham2016r]

# A draft workplan
___

## Part I
___

### Friday, 2018-01-05

* 13:00 - 16:00
    * [Introduction](pre_intro.html) - bte
    * [Getting data into R](pre_data.html) - bte
    
### Monday, 2018-01-08

* 13:00 - 16:00 [Getting started with ggplot](pre_ggplot1.html) - eh

### Tuesday, 2018-01-09

* 09:00 - 12:00
    * [Getting started with dplyr](pre_transformation1.html) - eh
    * [dplyr - combining tables](pre_transformation2.html) - eh

### Friday, 2018-01-12

* 09:00 - 12:00
    * [Working with (mfri) databases and introduction to the mar-package](pre_mar.html) - bte
* 13:00 - 16:00
    * [Spatial data and ggplot](pre_ggplot2.html) - eh

### Monday, 2018-01-15

* 09:00 - 12:00
    * [Reproducible research with R](404page.html) -nn
    * [Case example 1](404page.html) - nn

### Tuesday, 2018-01-16

* 09:00 - 12:00
    * [Working with time](404page.html) - nn
    * [Working with strings](404page.html) - nn

### Friday, 2018-01-19

* 13:00 - "Happy hour"
    * [To be dermined](404page.html)
    * [Next steps](404page.html)

## Part II
___

... to be announced, "data call" to be made, instructors to be found.

So far, informal discussion have resulted in having introduction to the following topics:

* [Geocomputation with R](https://bookdown.org/robinlovelace/geocompr/intro.html) - nn
* [Creating Websites with R Markdown](404page.html) - nn


## Addendums

* [Bits and pieces](bits_and_pieces.html) - collection of code made in response to the lectures.

# Citations
___


